name: Feature Request
description: Suggest a new feature or improvement to the game
title: "[FEATURE] "
labels: [enhancement, feature]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to propose a new feature or enhancement. Be clear and concise about the value it adds to the game.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the feature you'd like to see?
      placeholder: |
        Add a weather system that influences bee behavior and honey production. 
        Rainy days might reduce outside activity, while sunny days improve foraging.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature useful?
      description: Explain how this feature benefits gameplay or improves the experience.
      placeholder: |
        It adds atmosphere and gameplay depth, creating more interesting decision-making moments for players. 
        Encourages planning and makes the world feel more dynamic.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What needs to be implemented for this feature to be considered complete?
      placeholder: |
        - [ ] Weather system is implemented with at least 2 types: Sunny and Rainy
        - [ ] Weather changes randomly or based on time progression
        - [ ] Bees behave differently depending on weather
        - [ ] Visual indicators (e.g., rain animation, sun overlay)
    validations:
      required: true
